create table if not exists public.sorteos_semanales (
  id bigint generated by default as identity primary key,
  ganador_id uuid not null references public.usuarios_externos(id) on delete cascade,
  fecha_sorteo date not null,
  semana_inicio date not null,
  premio text not null default '1 entrada gratis',
  admin_ejecutor text,
  created_at timestamptz not null default now()
);

create index if not exists sorteos_semanales_semana_inicio_idx
  on public.sorteos_semanales (semana_inicio);

create index if not exists sorteos_semanales_ganador_id_idx
  on public.sorteos_semanales (ganador_id);
