create table if not exists public.alertas_paquetes (
  id bigint generated by default as identity primary key,
  registro_paquete_id uuid not null references public.registro_entrenamientos(id) on delete cascade,
  usuario_id uuid not null references public.usuarios_externos(id) on delete cascade,
  paquete_nombre text not null,
  entradas_restantes integer not null check (entradas_restantes >= 0),
  fecha_compra date,
  estado text not null default 'activa' check (estado in ('activa', 'resuelta')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint alertas_paquetes_registro_paquete_id_key unique (registro_paquete_id)
);

create index if not exists alertas_paquetes_usuario_id_idx
  on public.alertas_paquetes (usuario_id);

create index if not exists alertas_paquetes_estado_idx
  on public.alertas_paquetes (estado);
